stages:
  preprocess_data:
    cmd: python src/data/make_dataset.py data/raw/train.csv data/interim/train.pkl data/interim/target.pkl #python src/data/make_dataset.py  data/raw/test.csv data/processed/test.pkl
    deps:
    - data/raw
    # outs:
    # - data/interim
