stages:
  preprocess_data:
    cmd: python src/data/make_dataset.py data/raw/train.csv data/interim/train.pkl
      data/interim/target.pkl                                                                              #python src/data/make_dataset.py  data/raw/test.csv data/processed/test.pkl
    deps:
    - data/raw
    # outs:
    # - data/interim
  train_val_split:
    cmd: python src/data/train_val_split.py data/interim/train.pkl data/interim/target.pkl
      data/processed
    deps:
    - data/interim
    # outs:
    # - data/processed
  feature_generating:
    cmd: python src\features\build_features.py data/processed
    deps:
    - data/processed
  train_models:
    cmd: python src/models/train_model.py data/processed/ models/
    # deps:
    # - /src/features
  creating_pipelines:
    cmd: python src\models\create_pipelines.py models/ models/
    deps:
    - models/
  eval_models_print_graphs:
    cmd: python src/evaluate.py

  model_predict:
    cmd: python src/models/predict_model.py data/raw/test.csv data/predictions.csv
      models/catboost_model.pkl
    deps:
    - data/raw
